
#*************** ensenso_nx node and capture parameters ************************

#serial number (i.e. 171416 or 171417)
serial_number: "171417"

#run mode: run mode: 0->SERVER, 1->PUBLISHER
run_mode: 1

#loop rate in hz (good values: 20 when SERVER, 1 when PUBLISHER)
rate: 1

#frame name to which point cloud is referenced (relative, without namespace)
frame_name: "ensenso_nx_1/camera_lens_left"

#capture autoexposure [t/f]
auto_exposure: True

#use rgbd
rgbd: False

#capture exposure time [ms]
exposure_time: 0

#Dense cloud: 1->Node returns a dense cloud (ordered). 0->Node returns a non-dense cloud (unordered)
dense_cloud: 1
